version: '3'

services:
   mysql:
     build: docker/mysql
     environment:
       MYSQL_ROOT_PASSWORD: xxx
       MYSQL_DATABASE: knigoed
       MYSQL_USER: knigoed
       MYSQL_PASSWORD: xxx
     ports:
       - "3306:3306"