version: '3.3'
services:
   mysql:
     # mysql -h172.19.0.1 -P3306 -uroot -pqwerty
     # mysql -h172.19.0.1 -P9306
     build: docker/mysql
     environment:
       MYSQL_ROOT_PASSWORD: qwerty
       MYSQL_DATABASE: knigoed
       MYSQL_USER: knigoed
       MYSQL_PASSWORD: qwerty
     ports:
       - "3306:3306"
     #volumes:
     #  - ./docker/mysql/data:/var/lib/mysql

   sphinx:
     build: docker/sphinx
     ports:
       - "9306:9306"
       - "9312:9312"
     depends_on:
       - mysql
     command: mysql:3306 -s -t 30 -- /sbin/my_init

   #jetty:
   #  build: docker/jetty
   #  volumes:
   #    #- ./docker/jetty/jetty-deploy.xml:/var/lib/jetty/webapps/ROOT/jetty-deploy.xml
   #    - ./docker/jetty/jetty-deploy.xml:/usr/local/jetty/etc/jetty-deploy.xml
   #  ports:
   #    - "80:8080"
   #  depends_on:
   #    - mysql
   #    - sphinx
   #  command: sphinx:9306 -s -t 30 -- java -jar /usr/local/jetty/start.jar